### ISSUE TITLE
Making the Building System better

### ISSUE THREAD

**Issue by Chronophylos** [Omnomios/DynamicBulwarks#10]
My ideas are:
* Allow picking up barriers
* Allow rotating barrieres
* Moving barriers up/down should actually move the up/down by an absulute value
* Platforms for making fancy castles

**Comment by BeardedBushman** [comment]
In a scenario I play called "[CO 72] Operation Arrowhead - Takistan" by XFIRE Army on SW:
https://steamcommunity.com/sharedfiles/filedetails/?id=1234171508
You have a mobile arsenal that you can rotate to any angle and drop it just like your arsenal but it also allows you to "snap to terrain" option for angled placement on any surface, that would be ideal for placing objects for you base, maybe then the AI wouldn't walk right through double H barriers, just a suggestion.

**Comment by thatParadox** [comment]
Enhancements added.

Added ability to pick items up - to pick up and item no other players can be within 5m to prevent trolling.

Moving objects up and down should now be precisely 0.5 meters.  

When placed the object snaps to terrain

Rotate unnecessary as you can pick the item up and move to rotate it.

Added some more items that you can build

**Comment by Chronophylos** [comment]
Nice!
