### ISSUE TITLE
AI cleanup still failing occassionally

### ISSUE THREAD

**Issue by thatParadox** [Omnomios/DynamicBulwarks#11]
AI that are not visible on the map will still fail to be deleted from time to time.

Need to test KnowsAbout levels and instead of deleting the AI if it hasn't moved, delete the AI if it hasn't moved closer to the player instead.

**Comment by forsaken296** [comment]
you could also set it to delete an AI 2 min after they spawn if they are outside the circle still.  I don't know if its possible, but if it is, it could help with the issues.

**Comment by thatParadox** [comment]
Update pushed to Development.

Took this out of the mission loop and stuck it in it's own script. 
Changed it so AI must be moving towards the player. Script checks every 3 seconds if an AI is closer. Get deleted if it is unknown to WEST and further away than 20 meters.
