### ISSUE TITLE
People who join mid-match can't collect Ammo Drops that are already in the field

### ISSUE THREAD

**Issue by thatParadox** [Omnomios/DynamicBulwarks#12]

**Comment by forsaken296** [comment]
I think i know why bugs that involve mid match joining happen.  It doesn't always count them as part of the group of survivors.  Happened to a buddy of mine the other night, he joined, was running around getting gear, i went down, and we failed, even though he was still up. I have no idea how to replicate it other than attempting mid match joining repeatedly though.

**Comment by thatParadox** [comment]
Thanks forsaken. I think I know why that happens. We currently build an array of players at the beginning of the round. JIP players wouldn't be included.

**Comment by thatParadox** [comment]
JIP set to true on addaction for this. Should be fixed, needs play testing.

**Comment by thatParadox** [comment]
Has been fixed
