### ISSUE TITLE
Add Medkits to Bulwark parameter doesn't appear to work on dedicated

### ISSUE THREAD

**Issue by thatParadox** [Omnomios/DynamicBulwarks#13]

**Comment by Bobjobob24** [comment]
Navigate to `../bulwark/createBase.sqf`

Open `createBase.sqf`

Find line #31 which should read: `bulwarkBox addItemCargo ["Medikit", BULWARK_MEDIKITS];`


**Change line #31 to:** `bulwarkBox addItemCargoGlobal ["Medikit", BULWARK_MEDIKITS];`

**Comment by martindisch** [comment]
Nicely spotted, I went ahead and fixed it.
