### ISSUE TITLE
Magazine repack not needed with ACE3

### ISSUE THREAD

**Issue by FalcoGer** [Omnomios/DynamicBulwarks#138]
I don't want the magazine repack, or at least not on ctrl + r because ACE3 already has a function for that.
How can I disable that feature? Now every time I want to check my magazine my guy just crouches down and plays with the dirt for 10 seconds for no reason.

**Comment by thatParadox** [comment]
This mission is not designed to be compatible with ACE. It does not fit with our vision of what the mission should be or how it should be played. We do our best to make the mission play well with mods but ACE compatibility is not a goal.
