### ISSUE TITLE
Default loadout overwritten at mission start

### ISSUE THREAD

**Issue by FalcoGer** [Omnomios/DynamicBulwarks#139]
I wanted to have some starting stuff for the players (such as common uniform, some ACE3 tools such as map tools) and other items, such as GPS, a radio, etc.

So I opened the mission and edited the civilians to have the stuff I want the players to get. However after mission start everything is deleted.

**Comment by thatParadox** [comment]
Yes, all gear gets deleted in onPlayerRespawn. Script any gear you need there.
