### ISSUE TITLE
Can not disable revive

### ISSUE THREAD

**Issue by FalcoGer** [Omnomios/DynamicBulwarks#140]
I want to use the ACE medical system instead of the vanilla revive. However there is no way to disable the revive system in the editor it seems. How do I make it happen?

I also don't want the vanilla Medkits/FAKs to spawn.

**Comment by thatParadox** [comment]
This mission is not designed to be compatible with ACE. It does not fit with our vision of what the mission should be or how it should be played. We do our best to make the mission play well with mods but ACE compatibility is not a goal.
