### ISSUE TITLE
Loot blacklist not working on dropped ammo box

### ISSUE THREAD

**Issue by FalcoGer** [Omnomios/DynamicBulwarks#141]
After picking up a dropped box I got this error:
![grafik](https://user-images.githubusercontent.com/16250196/120249286-abdb3280-c27a-11eb-88ba-5d8e0455efc1.png)

On top of that I get M200 (Blank) rounds, which I have explicitly forbidden.
![grafik](https://user-images.githubusercontent.com/16250196/120249195-61f24c80-c27a-11eb-931f-18e685913d1f.png)

I also got slugs and tube launched flare grenades, which my weapon doesn't fire.

**Comment by thatParadox** [comment]
Supply drops are not intended to work with the blacklist. Again, for help with modifying the mission please use the discord: https://discord.gg/fEbp7zH

This section is intended for problems found in the vanilla mission.
