### ISSUE TITLE
Players are spawned away from the Bulwarks Box

### ISSUE THREAD

**Issue by RJL1100** [Omnomios/DynamicBulwarks#145]
This has happened a number of time around wave 6 or 7 when looting AI the player is spawned outside the containment area.
When the player returned to their base there were AI inside the base.
AI are still walking through walls

**Comment by thatParadox** [comment]
That is a special wave where the Bulwark gets overrun and you have to take it back from the AI.

AI walking through walls is an ARMA bug. We've done what we can to overcome it.
