### ISSUE TITLE
Host in MP gets stuck in Spectator Cam after respawn

### ISSUE THREAD

**Issue by thatParadox** [Omnomios/DynamicBulwarks#20]
Often after dying the host in a multiplayer match (not dedicated) will get stuck in the spectator cam when they respawn.

**Comment by thatParadox** [comment]
Fix pushed, needs testing.

**Comment by tiwaz1994** [comment]
You can get out of the spectator cam by clicking on "spectator" in your "esc" menu.
Just as an easy workaround till its fixed.

**Comment by RotasOpera** [comment]
Maybe this will help: I've exported a pbo so we can run the mission on a dedicated server. Everytime the player in the first slot respawns, he is stuck in spectator cam. In this case the player has to rejoin to play again. Other players don't have this issue.

**Comment by thatParadox** [comment]
Added more Force Perspective's to the mission. Seems to be fixed from testing so far.
