### ISSUE TITLE
Suggestion: MONEY POOL

### ISSUE THREAD

**Issue by BeardedBushman** [Omnomios/DynamicBulwarks#21]
Just a thought. MONEY POOL
If you had a cash register/bench that you could move like the Arsenal, you could use it to pool money to be spent on fortifications, example, if someone needs to leave the game and they have 200k, they can store that money in the cash register for others to use to keep building the base, maybe make it a "money pool" option in the parameters or something.

**Comment by thatParadox** [comment]
Good idea, thanks for mentioning it. Will close this "Issue" and move it to the planned features. We'll see what we can do!

**Comment by BeardedBushman** [comment]
Cool mate :)
