### ISSUE TITLE
The buyable Storage crates can get destroyed

### ISSUE THREAD

**Issue by tiwaz1994** [Omnomios/DynamicBulwarks#22]
Had this happen a few times.

**Comment by Omnomios** [comment]
You'll need to provide a bit more information. Do you mean that they disappear by themselves? When you shoot them, they explode? You can destroy them with the action menu?

**Comment by tiwaz1994** [comment]
Sorry did not think much about this when adding the issue. 
They can get destroyed by explosives, by gunfire and if a vehicle drives over/near them.

Also the guard tower and other props that can be destroyed, get destroyed by explosives. Destroyed guard towers stay arround broken and you can't delete them. I'd suggest make all placeables invincible.

**Comment by thatParadox** [comment]
After consideration, we want these to be able to be destroyed. It makes the player think about how they will design their Bulwark.
