### ISSUE TITLE
Night Vision/Night Time/Arsenal Issues

### ISSUE THREAD

**Issue by BeardedBushman** [Omnomios/DynamicBulwarks#25]
There seems to be a problem with night vision in the params, you do not spawn with NVG's when set to yes and attempting to play at night (6pm-4am) also I've noticed twice the arsenal spawns with flares on it at night, when the flares stop the arsenal falls through the map. You can check my twitch channels latest stream for video of this.
Check at 23:40
https://www.twitch.tv/videos/274272914
Edit: played at night for a while and never found any nvg as loot.

**Comment by cody0520** [comment]
class PLAYER_STARTNVG
	{
		title = "Players start with NVG";
		values[] = {0, 1};
		texts[] = {"No", "Yes"};
		default = 1;
	};



this is how i have mine,  and sometimes we do start with NVG's and other times we dont :/

**Comment by thatParadox** [comment]
Fixed. Sorry it took a while to find. Will be in 1.5 release.

_player linkItem "Integrated_NVG_F";
