### ISSUE TITLE
lootHolder does not get removed on take action

### ISSUE THREAD

**Issue by Vehementis** [Omnomios/DynamicBulwarks#31]
If you take any loot drop from _lootHolder using the action-menu the empty _lootHolder won't get deleted.
This is because the _lootHolder cleanup is done on "ContainerClosed" event.
The best solution would be using WeaponHolderSimulated instead of WeaponHolderSimulated_Scripted because the game would take care about cleanup, BUT WeaponHolderSimulated will often get cleaned up before you can add something. I'm not sure if it is easier to fix the WeaponHolderSimulated auto cleanup or to get the WeaponHolderSimulated_Scripted manual cleanup right.

**Comment by thatParadox** [comment]
Possible solution

Take
Arguments of this scripting command don't have to be local to the client the command is executed on
Triggers when a unit takes an item from a container.

this addEventHandler ["Take", {
	params ["_unit", "_container", "_item"];
}];
unit: Object - Unit to which the event handler is assigned
container: Object - The container from which the item was taken (vehicle, box, etc.)
item: String - The class name of the taken item

**Comment by thatParadox** [comment]
I added an event to the player to delete them once they are empty.

[player, ['Take', {
  params ['_unit', '_container', '_item'];
  [_container] remoteExecCall ["loot_fnc_deleteIfEmpty", 2];
}]] remoteExec ['addEventHandler', 0, true];

Sorry this one took a while. I had no idea about that Event Handler but stumbled across it while working on something else and thought of this.
