### ISSUE TITLE
Bulwark Box is Destroyed on Mission Start

### ISSUE THREAD

**Issue by big-corey** [Omnomios/DynamicBulwarks#33]
As the title suggests, the Bulwark Box is often destroyed (i.e., it burns and shakes into oblivion) on mission start, thereby ruining the match and forcing me to restart repeatedly until the Dynamic Bulwarks mission generator finally produces a mission without the Bulwark Box being destroyed immediately. 

Oddly, although this happens maybe 3/4 times that I try to start a mission (even without any mods) in Tanoa, it does not happen at all in Lythium. Since I have everything (OS and applications) loaded on an SSD, I have fast load times. Thus, my guess is that the mission is loading before the script to have the Bulwark Box be non-destructable has time to run. The problem is probably fixed in Lythium do to a slightly slower loading time. Again, however, this is simply a guess as to what the underlying problem is.

**Comment by thatParadox** [comment]
Fixed:

createBase.sqf

_bulMon allowDamage false;
bulwarkBox allowDamage false;
