### ISSUE TITLE
Bulwark allows you to buy second object while still holding the first

### ISSUE THREAD

**Issue by Omnomios** [Omnomios/DynamicBulwarks#34]
"When clicking buy twice for a structure it will make it so you can only place one down, then it will have you hold the other one but you are unable to put it down. It blocks ur entire front view pretty much"

**Comment by thatParadox** [comment]
Tested in MP (Not Dedicate) and I do not replicate the problem. Will test in Dedicated at a later date and will reopen if necessary.
