### ISSUE TITLE
Unreliable Mid Match Joining

### ISSUE THREAD

**Issue by Omnomios** [Omnomios/DynamicBulwarks#4]
I dont know if this can be fixed, but often when a player joins mid game, they will end up in the ocean and from then on unless the server is restarted it leaves one player stuck in the ocean.

**Comment by thatParadox** [comment]
New areaEnforcement.sqf collects all HeadlessClient_F each time it loops and is constantly doing this. New players should be picked up and TP'd if they spawn in the ocean.

**Comment by thatParadox** [comment]
Just had this happen to me joining mid match, was stuck in the ocean. Not fixed.

**Comment by thatParadox** [comment]
Seems to be related to moving the Bulwark box too far from it's orginal location

**Comment by thatParadox** [comment]
Fix by Omnom push in 1.2
