### ISSUE TITLE
Placing Down Object While Sprinting Makes Object Kill You If You Collide

### ISSUE THREAD

**Issue by Jarple** [Omnomios/DynamicBulwarks#48]
If you sprint while holding a building object purchased from the bulwark, then place it down while continuing to sprint, that object will now hurt/kill you if you touch it at any point (no matter the distance that the object was away from you before placing it down).

Only way to fix is to place objects down when player is 100% stationary and/or to re-pick up that object up and place it back down while being still.

**Comment by thatParadox** [comment]
Removed collision damage from mission (Fall damage etc) for 1.5

Confirmed that now if you place an object while sprinting you will ragdoll but not die. Not ideal but much better than dying. Not much we can do as it's all to do with the arma physics engine.
