### ISSUE TITLE
Enemies walking through fortifications.

### ISSUE THREAD

**Issue by Omnomios** [Omnomios/DynamicBulwarks#5]
I have no idea why it happens and cant offer any actual fixes, but you may want to take a look at how KP Liberation missions spawn/place structures, since AI cannot go through those, even ask if you can borrow some code from them.

**Comment by thatParadox** [comment]
Did some research. This is an ARMA bug, not a mission bug. If you want objects that you place to prevent enemies from walking through them then they must placed be on perfectly flat / level surfaces.

**Comment by Omnomios** [comment]
I've had it happen on the opening of hangars. Completely flat concrete. There has to be something we can do as a workaround, like attaching objects that are long with good collision meshes that compensate for the shitty ones.

**Comment by Omnomios** [comment]
Closing this. There's not much we can do about it.
