### ISSUE TITLE
BULWARK_LOCATION = List_LocationMarkers in editMe.sqf causes failure in fn_bulwarkLocation.sqf

### ISSUE THREAD

**Issue by Doctor-Butts** [Omnomios/DynamicBulwarks#53]
Error seems to be around here:

```
_probe = createVehicle ["Sign_Arrow_F", [0,0,0], [], 0, "CAN_COLLIDE"];
while {isNil "_finalPos"} do {
	_city = selectRandom _locations;
	_houses = nearestObjects [_city, ["house"], 300];
```
Error is:
`Error undefined variable in expression _city`

On script failure, the Bulwark box spawns at the ocean platform and does not teleport anywhere.

If location is set to ListAllCities in editme.sqf, there is no failure.

**Comment by Doctor-Butts** [comment]
A fix:
I commented out all of this code in locationLists.sqf:
```
{
    _currMarker = toArray _x;
    if(count _currMarker >= 4) then {
        _currMarker resize 8;
        _currMarker = toString _currMarker;
		if
        if(_currMarker == "bulwark_") then {
            _zoneMarkers append [getMarkerPos _x];
            deleteMarker _x;
        };
    };
} foreach allMapMarkers;
```

I then placed Large Yellow Arrows, turned off simulation and show model in areas where I wanted a location. I then used the following code to get locations:
```
_arrowLocations = [];
{
    _arrowLocations append [getPos _x];
} foreach (allMissionObjects "Sign_Arrow_Large_Yellow_F");
```

It now works.

**Comment by Omnomios** [comment]
What map does this happen on?

**Comment by ChronosWS** [comment]
Closing, there's been a lot of changes since the big Tiwaz merge. Re-open if this is still a problem.
