### ISSUE TITLE
StartMAP/NVG doesn't work

### ISSUE THREAD

**Issue by Sqwince** [Omnomios/DynamicBulwarks#54]
The paramters start with map/nvg don't work properly.

**Comment by Omnomios** [comment]
Hey Sqwince. Can you provide more info on the error?

I can't recreate the problem if I don't know exactly what the problem is. Everything in ArmA "don't work properly" so it's hard to narrow it down.

Can you write down:
1) What you did.
2) What you expected.
3) What the mission did.

**Comment by TheSniperFan** [comment]
We have the same problem on our server with `PLAYER_STARTNVG` and `PLAYER_STARTWEAPON`.

**The problem:**
* Characters don't reliably spawn with the items
* Sometimes you get a pistol, sometimes you get NVGs, sometimes you get both, sometimes you get neither
* Varies across players on the servers, so one might get a pistol while others get nothing
* Mission parameters during role selection say the options are enabled

**The relevant part from our `server.cfg`:**
```c++
class Missions {
	class BullwarksZombies {
		template = "DynamicBulwarksZombies.Altis"
		difficulty = "Regular";

		class Params {
			DOWN_TIME = 60;
			PLAYER_STARTWEAPON = 1;
			PLAYER_STARTNVG = 1;
			ZOMBIE_JUMP = 3;
			ZOMBIE_DEMON_JUMP = 3;
			DAY_TIME_FROM = 20;
			DAY_TIME_TO = 20;
			ReviveRequiredItems = 0;
			BULWARK_RADIUS = 200;
		};
	};
	...
};
```

The other options (like the time of day) work fine, so our `server.cfg` seems to work fine.

**Comment by thatParadox** [comment]
Thanks for the fix @TheSniperFan ! I didn't merge it because I made a bunch of changes, easier to just copy and paste it in. Cheers again!!
