### ISSUE TITLE
Friendly Reminder To Make The Cold War Version Available

### ISSUE THREAD

**Issue by LuizBarros99** [Omnomios/DynamicBulwarks#55]
Just a quick friendly reminder to make the "Cold War" assets version available here, so that we may be able to play it in other maps. (https://steamcommunity.com/sharedfiles/filedetails/?id=1732998686)

**Comment by Omnomios** [comment]
Thanks for the reminder. I've created the branch but I need to get the source off Hilltop.
He's been MIA the last week or so. I'll hit him up as soon as I can.

**Comment by thatParadox** [comment]
Thanks for the reminder LuizBarros99 and thanks Omnom for creating the branch! I've updated the branch published the Cold War release.

https://github.com/Omnomios/DynamicBulwarks/releases/tag/CW1.0

Always better to go to the GitHub than the steam page to get stuff done, ha ha.
