### ISSUE TITLE
Clients stuck on infinite loading screen when joining.

### ISSUE THREAD

**Issue by MooseOnTheLoose1** [Omnomios/DynamicBulwarks#56]
all players attempting to join get stuck at a infinite load screen, running on dedicated server, only a few mods.

**Comment by MooseOnTheLoose1** [comment]
To add some info, players characters are loading into the correct spot on the map, right next to the bulwark, and if the server shuts down while i am loading in i can see where my char was, however until then the only thing i can see is the loading screen, all keyboard and mouse inputs are working and characters respond in game, eg if someone on the loading screen hits W, his char will walk forwards in game.

**Comment by thatParadox** [comment]
I haven't replicated the problem. It's either mods or the mission is corrupt. Try downloading the mission again.
