### ISSUE TITLE
Medikit auto revive uses all Medikits in player's inventory.

### ISSUE THREAD

**Issue by thatParadox** [Omnomios/DynamicBulwarks#58]
If the player has more than one medikit in their inventory the auto revive system uses them all. It should only need one.

**Comment by thatParadox** [comment]
Fixed. Loop was going too quickly and using medikits before the incapacitated state ended.

Now checks for RevByMedikit variable.

**Comment by Kern3LP4niK** [comment]
Adding this line stopped my players from being able to revive with medikit.  Removing the line consistently re-enabled the ability to auto-revive while carrying medikit.  I could not reproduce the issue of using multiple medikits after removing the following portion of line 8
 " && !(_playerInvToCheck getVariable "RevByMedikit") "
