### ISSUE TITLE
Placing Objects

### ISSUE THREAD

**Issue by Zippy-91** [Omnomios/DynamicBulwarks#64]
If you pick up another object whilst carrying an object already you're able to bug it out and have a permanent object in front of you and the only way to remove it is to exit to lobby.

So you can walk around with a small sandbag as your own personal shield.

**Comment by thatParadox** [comment]
Thanks for the heads up! I have added a check when you pickup an item to stop this from happening in 1.5.

fn_pickup.sqf:

if (!(player getVariable "buildItemHeld")) then {

Stuff

} else {

	[format ["<t size='0.6' color='#ff3300'>You're already carrying an object!</t>"], -0, -0.02, 2, 0.1] call BIS_fnc_dynamicText;

};
