### ISSUE TITLE
Keep getting heavy fire from AI when Incapacited/waiting for revive.

### ISSUE THREAD

**Issue by EngineerWAK** [Omnomios/DynamicBulwarks#70]
I'm testing v1.5b5 and every time I get "incapacited", no mater the time I put for the revive option, I keep getting shot from everywhere, I don't remember having this problem in the v1.4, I didn't try the other v1.5b.
Thanks for your work tho, its pretty interesting.
[EDIT] It's running on a dedicated server.
![20190627223123_1](https://user-images.githubusercontent.com/37033689/60276363-0d2b5600-992e-11e9-8f27-75ba354b9fc2.jpg)

**Comment by thatParadox** [comment]
Thanks for letting us know. Is this while you're being revived by a medikit? I'm not sure I know what "no mater the time I put for the revive option" is referring to?

**Comment by EngineerWAK** [comment]
yes, while being revived by the medikit(s).
I'm talking about this "time":
`
	class RESPAWN_TIME
	{
		title = "Respawn Time";
		values[] = {0, 5, 10, 20, 30};
		texts[] = {"0", "5", "10", "20", "30"};
		default = 5;
	};`

**Comment by thatParadox** [comment]
Sorry, by a player or one in you inventory?

**Comment by EngineerWAK** [comment]
by the one in the inventory, I didn't know we can revive other players xD

**Comment by thatParadox** [comment]
Ah, yeah you won't enter the INCAPACITATED state anymore. We've just reworked it. You will just play an animation. AI will probably keep shooting at you be you're immune to damage for 10 seconds after using the medikit so it doesn't matter.

Thanks for letting us know, though!! Keep the bug reports coming!
