### ISSUE TITLE
Error with the civilian spawn

### ISSUE THREAD

**Issue by EngineerWAK** [Omnomios/DynamicBulwarks#71]
Every time one of those "CivilianPresence_C_man_xxxx" spawn, it spam the RPT with thousands of errors, I got the same problem on Exile Servers:
**17:18:41 "||WAK_DEBUG|| Spawn Civilian || Wave 5, group C Alpha 4-2, Class CivilianPresence_C_man_polo_4_F_euro"
17:19:18 Error in expression <[];
 _threat = [_this,_threatsNew] call bis_fnc_cp_main;
 _t = time + (_this ca>
 17:19:18   Error position: <bis_fnc_cp_main;**

**Comment by thatParadox** [comment]
It's an ARMA bug, we can't do anything about it. Thanks for the head up, though!
