### ISSUE TITLE
Pillbox placement issue

### ISSUE THREAD

**Issue by anfo55** [Omnomios/DynamicBulwarks#79]
G'day

Moving the concrete pillbox (cost 4500) goes awry. You start by looking at the outside of the pillbox to pickup. When moving and within sometimes 3 or more seconds, you will be suddently facing 90 degrees to your original orientation. This puts you physically inside the pillbox making final placement difficult.

**Comment by ChronosWS** [comment]
All placement issues like this (including small ramp, halogen light, etc) should be fixed after the big Tiwaz merge.
