### ISSUE TITLE
Medkits doesn't revive everytime

### ISSUE THREAD

**Issue by tiwaz1994** [Omnomios/DynamicBulwarks#93]
copy of: https://github.com/tiwaz1994/DynamicBulwarks/issues/58

Sometimes, when the player dies with a medkit in his backpack, the medkit does not revive the player.
I think that this bug happens when we take a lot of damages (maybe explosions or high calibers),
or it can happens when the player is in run's animation (something like that).

**Comment by ChronosWS** [comment]
Fixed in big Tiwaz merge
